"""
Django settings for timberproject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')%x&ph-7&waf#(_ntrakrf$9m)&2_!ae%8rcd$rai4p*mw)02='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

#SERVER_BASE_URL='http://127.0.0.1:8000/'

SERVER_BASE_URL = 'http://65.1.132.43:8080/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_app',
    'knox',
    'rest_apis',
    'rest_framework',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ]

}

ROOT_URLCONF = 'timberproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'timberproject.wsgi.application'
AUTH_USER_MODEL = 'my_app.CustomUser'
# AUTH_USER_MODEL = 'my_app.CustomUser'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'Timber_db',
#        'USER': 'postgres',
#        'PASSWORD':'admin',
#        # 'HOST':'database-2.ckpvghnbqfb8.us-east-2.rds.amazonaws.com',
#        'HOST' : 'localhost',
#        'PORT': '5433',
#    }
# }

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       # 'NAME': 'Timber_db',
       'NAME': 'Timber_db2',
       'USER': 'postgres',
       'PASSWORD':'postgres',
       # 'HOST' : 'database-2.cxt35h3oleim.ap-south-1.rds.amazonaws.com',
       'HOST' : 'database-3.cxt35h3oleim.ap-south-1.rds.amazonaws.com',
       'PORT': '5432',
   }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/


# ######################################
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'asky.nade@gmail.com'
# EMAIL_HOST_PASSWORD = 'Akassh10081991'


# TWILIO_ACCOUNT_SID = "ACf90f4156739912446e2be5eceed59b6c"
# TWILIO_AUTH_TOKEN = "6efa18f8237e60465a5839833b06f707"
# TWILIO_NUMBER = "+12512379710"




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'

PHOTO_PROOF_PATH = 'static/media/upload/photo_proof/'

AADHAR_IMAGE_PATH = 'static/media/upload/aadhar_card/'

REVENUE_APPLICATION_PATH = 'static/media/upload/revenue_application/'

REVENUE_APPROVAL_PATH = 'static/media/upload/revenue_approval/'

DECLARATION_PATH = 'static/media/upload/declaration/'

LOCATION_SKETCH_PATH = 'static/media/upload/location_sketch/'

TREE_OWNERSHIP_PATH = 'static/media/upload/tree_ownership/'

PROOF_OF_OWNERSHIP_PATH = 'static/media/upload/proof_of_ownership/'

LICENSE_PATH = 'static/media/upload/license/'

SIGN_PATH = 'static/media/upload/signature/'

PROFILE_PATH = 'static/media/upload/profile/'

NO_PROFILE_PATH = 'static/images/noprofile.jfif'

QRCODE_PATH = 'static/media/qr_code/'

USAID_LOGO = 'static/media/logo/USAID_LOGO.png'

KERALAFOREST_LOGO = 'static/media/logo/KeralaForest.PNG'

MEDIA_URL = "/media/"

MEDIA_DIR = os.path.join(BASE_DIR,'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

DEFAULT_LOGO = 'static/images/default_logo.png'

NO_IMAGE = 'static/images/no_image.png'

MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = 'dashboard'

LOGIN_URL = 'user_login'

#SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_COOKIE_AGE = 60*60*4
