# Generated by Django 3.1.7 on 2021-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
