# Generated by Django 3.1.7 on 2021-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210315_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_detials',
            name='driver_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
