# Generated by Django 3.1.7 on 2021-03-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210316_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='timberlogdetails',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timberlogdetails',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransitPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_code_img', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_phone', models.CharField(max_length=20, unique=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=200, null=True)),
                ('license_image', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_of_vehicle_with_number', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('taluka', models.CharField(blank=True, max_length=255)),
                ('block', models.CharField(blank=True, max_length=255)),
                ('village', models.CharField(blank=True, max_length=255)),
                ('app_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitpass_app', to='my_app.applicationform')),
            ],
        ),
    ]
