# Generated by Django 3.1.7 on 2021-03-17 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210317_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='deputy_officer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='range_officer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='verify_office_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitpass',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_status',
            field=models.CharField(choices=[('S', 'Submitted'), ('P', 'Pending'), ('A', 'Approved')], default='S', max_length=3),
        ),
    ]
