# Generated by Django 3.1.7 on 2021-03-18 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20210317_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='signature_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image_documents',
            name='signature_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
