# Generated by Django 3.1.7 on 2021-03-18 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20210318_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
