# Generated by Django 3.1.7 on 2021-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_applicationform_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='transit_pass_created_date',
            field=models.DateField(blank=True, default='2021-03-19', null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='transit_pass_id',
            field=models.IntegerField(default=0),
        ),
    ]
