# Generated by Django 3.1.7 on 2021-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20210319_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_status',
            field=models.CharField(choices=[('S', 'Submitted'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='S', max_length=3),
        ),
    ]
