# Generated by Django 3.1.7 on 2021-03-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20210321_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitpass',
            name='qr_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
