# Generated by Django 3.1.7 on 2021-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_transitpass_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_detail',
            field=models.CharField(default='', max_length=25),
        ),
    ]
