# Generated by Django 3.1.7 on 2021-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='trees_cutted',
            field=models.BooleanField(default=False),
        ),
    ]
