# Generated by Django 3.1.7 on 2021-04-14 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_applicationform_trees_cutted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
