# Generated by Django 3.1.7 on 2021-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_applicationform_application_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timberlogdetails',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timberlogdetails',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timberlogdetails',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
