# Generated by Django 3.1.7 on 2021-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20210415_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='timberlogdetails',
            name='log_qr_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timberlogdetails',
            name='log_qr_code_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
