# Generated by Django 3.1.7 on 2021-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20210420_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_proof_img',
            field=models.CharField(default='no_image.png', max_length=255),
        ),
    ]
