# Generated by Django 3.1.7 on 2021-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20210420_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitpass',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
