# Generated by Django 3.1.7 on 2021-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20210420_1052'),
    ]

    operations = [
       
    ]
