# Generated by Django 3.1.7 on 2021-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_auto_20210426_1521'),
    ]

    operations = [
      
    ]
