# Generated by Django 3.1.7 on 2021-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_auto_20210426_1522'),
    ]

    operations = [
       
    ]
