# Generated by Django 3.1.7 on 2021-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_auto_20210426_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='area_range',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='division',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='pincode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
