# Generated by Django 3.1.7 on 2021-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_auto_20210510_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='disapproved_reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='block',
            field=models.CharField(default='', max_length=255),
        ),
    ]
