# Generated by Django 3.1.7 on 2021-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_division_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
