# Generated by Django 3.1.7 on 2021-05-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_customuser_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='range_division', to='my_app.division'),
        ),
    ]
