# Generated by Django 3.1.7 on 2021-05-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0033_range_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('types', models.CharField(blank=True, default=True, max_length=150)),
                ('is_delete', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolemethod_parent', to='my_app.rolemethod')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_created_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.rolemethod')),
            ],
        ),
    ]
