# Generated by Django 3.1.7 on 2021-05-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_rolemethod_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueofficerdetail',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_div', to='my_app.division'),
        ),
        migrations.AddField(
            model_name='revenueofficerdetail',
            name='range_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_range', to='my_app.range'),
        ),
    ]
