# Generated by Django 3.1.7 on 2021-05-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_auto_20210530_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestofficerdetail',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fod_div', to='my_app.division'),
        ),
        migrations.AddField(
            model_name='forestofficerdetail',
            name='range_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fod_range', to='my_app.range'),
        ),
    ]
