# Generated by Django 3.1.7 on 2021-05-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20210530_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestofficerdetail',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='revenueofficerdetail',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
