# Generated by Django 3.1.7 on 2021-05-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0037_auto_20210530_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_group', to='auth.group'),
        ),
    ]
