# Generated by Django 3.1.7 on 2021-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_auto_20210601_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemethod',
            name='method_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
