# Generated by Django 3.1.7 on 2021-07-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0040_auto_20210601_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='approved_by_deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform_approved_by_deputy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='approved_by_revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform_approved_by_revenue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='is_noc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treespecies',
            name='is_noc',
            field=models.BooleanField(default=False),
        ),
    ]
