# Generated by Django 3.1.7 on 2021-07-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0042_applicationform_deemed_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='disapproved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform_disapproved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
