# Generated by Django 3.1.7 on 2021-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_applicationform_disapproved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='disapproved_by_grp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
