# Generated by Django 3.1.7 on 2021-07-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_applicationform_disapproved_by_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionOfficerdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=200, null=True)),
                ('office_address', models.CharField(blank=True, max_length=500, null=True)),
                ('div_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dod_div_user', to=settings.AUTH_USER_MODEL)),
                ('division_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dod_div', to='my_app.division')),
            ],
        ),
    ]
