# Generated by Django 3.1.7 on 2021-07-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0046_district_taluka_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='division_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='division_officer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='other_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='reason_division_officer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
