# Generated by Django 3.1.7 on 2021-07-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_applicationform_destination_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='approved_by_deputy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform_approved_by_deputy2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='deputy2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='is_form_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='reason_deputy2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='verify_deputy2',
            field=models.BooleanField(default=False),
        ),
    ]
