# Generated by Django 3.1.7 on 2021-07-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0050_auto_20210728_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species_geodetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('appform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_detaila_app_id', to='my_app.applicationform')),
                ('species_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_geodetails_species_name', to='my_app.treespecies')),
            ],
        ),
    ]
