# Generated by Django 3.1.7 on 2021-07-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0051_species_geodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='appsecond_one_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='appsecond_two_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
