# Generated by Django 3.1.7 on 2021-08-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0052_auto_20210729_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='log_updated_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
