# Generated by Django 3.1.7 on 2021-08-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0053_applicationform_log_updated_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='deemed_approval_1',
            field=models.BooleanField(default=False),
        ),
    ]
